defaults:
  - _self_
  - inference: inference_qwen2.5_7b

experiment:
  exp_name: qwen2.5_7b
  exp_dir: outputs/${experiment.exp_name}

  task:
    type: inference
    backend: vllm
    entrypoint: flagscale/inference/inference_qwen2.5.py
  runner:
    hostfile: null
  cmds:
    before_start: source activate flagscale
  envs:
    CUDA_VISIBLE_DEVICES: 4,5,6,7
    CUDA_DEVICE_MAX_CONNECTIONS: 1

action: run

hydra:
  run:
    dir: ${experiment.exp_dir}/hydra
